/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmeRouteImport } from './routes/adme'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DrugMemoryRouteImport } from './routes/drug-memory'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as PronunciationRouteImport } from './routes/pronunciation'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudyRouteImport } from './routes/study'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BrandsIdRouteImport } from './routes/brands.$id'
import { Route as ClassesIndexRouteImport } from './routes/classes.index'
import { Route as ClassesSlugRouteImport } from './routes/classes.$slug'
import { Route as ManufacturersIndexRouteImport } from './routes/manufacturers.index'
import { Route as ManufacturersIdRouteImport } from './routes/manufacturers.$id'
import { Route as MedicinesIndexRouteImport } from './routes/medicines.index'
import { Route as MedicinesSlugRouteImport } from './routes/medicines.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin.$id'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminManufacturersRouteImport } from './routes/_authenticated/admin.manufacturers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmeRoute = AdmeRouteImport.update({
  id: '/adme',
  path: '/adme',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DrugMemoryRoute = DrugMemoryRouteImport.update({
  id: '/drug-memory',
  path: '/drug-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciationRoute = PronunciationRouteImport.update({
  id: '/pronunciation',
  path: '/pronunciation',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIdRoute = BrandsIdRouteImport.update({
  id: '/brands/$id',
  path: '/brands/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesSlugRoute = ClassesSlugRouteImport.update({
  id: '/classes/$slug',
  path: '/classes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturersIndexRoute = ManufacturersIndexRouteImport.update({
  id: '/manufacturers/',
  path: '/manufacturers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturersIdRoute = ManufacturersIdRouteImport.update({
  id: '/manufacturers/$id',
  path: '/manufacturers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesIndexRoute = MedicinesIndexRouteImport.update({
  id: '/medicines/',
  path: '/medicines/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesSlugRoute = MedicinesSlugRouteImport.update({
  id: '/medicines/$slug',
  path: '/medicines/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminManufacturersRoute =
  AuthenticatedAdminManufacturersRouteImport.update({
    id: '/admin/manufacturers',
    path: '/admin/manufacturers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adme': typeof AdmeRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/drug-memory': typeof DrugMemoryRoute
  '/favorites': typeof FavoritesRoute
  '/flashcards': typeof FlashcardsRoute
  '/learn': typeof LearnRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/pronunciation': typeof PronunciationRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/terms': typeof TermsRoute
  '/brands/$id': typeof BrandsIdRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/manufacturers/$id': typeof ManufacturersIdRoute
  '/medicines/$slug': typeof MedicinesSlugRoute
  '/classes/': typeof ClassesIndexRoute
  '/manufacturers/': typeof ManufacturersIndexRoute
  '/medicines/': typeof MedicinesIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/manufacturers': typeof AuthenticatedAdminManufacturersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adme': typeof AdmeRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/drug-memory': typeof DrugMemoryRoute
  '/favorites': typeof FavoritesRoute
  '/flashcards': typeof FlashcardsRoute
  '/learn': typeof LearnRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/pronunciation': typeof PronunciationRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/terms': typeof TermsRoute
  '/brands/$id': typeof BrandsIdRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/manufacturers/$id': typeof ManufacturersIdRoute
  '/medicines/$slug': typeof MedicinesSlugRoute
  '/classes': typeof ClassesIndexRoute
  '/manufacturers': typeof ManufacturersIndexRoute
  '/medicines': typeof MedicinesIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/manufacturers': typeof AuthenticatedAdminManufacturersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/adme': typeof AdmeRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/drug-memory': typeof DrugMemoryRoute
  '/favorites': typeof FavoritesRoute
  '/flashcards': typeof FlashcardsRoute
  '/learn': typeof LearnRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/pronunciation': typeof PronunciationRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/terms': typeof TermsRoute
  '/brands/$id': typeof BrandsIdRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/manufacturers/$id': typeof ManufacturersIdRoute
  '/medicines/$slug': typeof MedicinesSlugRoute
  '/classes/': typeof ClassesIndexRoute
  '/manufacturers/': typeof ManufacturersIndexRoute
  '/medicines/': typeof MedicinesIndexRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/manufacturers': typeof AuthenticatedAdminManufacturersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adme'
    | '/auth'
    | '/compare'
    | '/drug-memory'
    | '/favorites'
    | '/flashcards'
    | '/learn'
    | '/learning'
    | '/login'
    | '/memory'
    | '/pronunciation'
    | '/quiz'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/study'
    | '/terms'
    | '/brands/$id'
    | '/classes/$slug'
    | '/manufacturers/$id'
    | '/medicines/$slug'
    | '/classes/'
    | '/manufacturers/'
    | '/medicines/'
    | '/admin/$id'
    | '/admin/import'
    | '/admin/manufacturers'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adme'
    | '/auth'
    | '/compare'
    | '/drug-memory'
    | '/favorites'
    | '/flashcards'
    | '/learn'
    | '/learning'
    | '/login'
    | '/memory'
    | '/pronunciation'
    | '/quiz'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/study'
    | '/terms'
    | '/brands/$id'
    | '/classes/$slug'
    | '/manufacturers/$id'
    | '/medicines/$slug'
    | '/classes'
    | '/manufacturers'
    | '/medicines'
    | '/admin/$id'
    | '/admin/import'
    | '/admin/manufacturers'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/adme'
    | '/auth'
    | '/compare'
    | '/drug-memory'
    | '/favorites'
    | '/flashcards'
    | '/learn'
    | '/learning'
    | '/login'
    | '/memory'
    | '/pronunciation'
    | '/quiz'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/study'
    | '/terms'
    | '/brands/$id'
    | '/classes/$slug'
    | '/manufacturers/$id'
    | '/medicines/$slug'
    | '/classes/'
    | '/manufacturers/'
    | '/medicines/'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/manufacturers'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdmeRoute: typeof AdmeRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  DrugMemoryRoute: typeof DrugMemoryRoute
  FavoritesRoute: typeof FavoritesRoute
  FlashcardsRoute: typeof FlashcardsRoute
  LearnRoute: typeof LearnRoute
  LearningRoute: typeof LearningRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  PronunciationRoute: typeof PronunciationRoute
  QuizRoute: typeof QuizRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StudyRoute: typeof StudyRoute
  TermsRoute: typeof TermsRoute
  BrandsIdRoute: typeof BrandsIdRoute
  ClassesSlugRoute: typeof ClassesSlugRoute
  ManufacturersIdRoute: typeof ManufacturersIdRoute
  MedicinesSlugRoute: typeof MedicinesSlugRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  ManufacturersIndexRoute: typeof ManufacturersIndexRoute
  MedicinesIndexRoute: typeof MedicinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adme': {
      id: '/adme'
      path: '/adme'
      fullPath: '/adme'
      preLoaderRoute: typeof AdmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drug-memory': {
      id: '/drug-memory'
      path: '/drug-memory'
      fullPath: '/drug-memory'
      preLoaderRoute: typeof DrugMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronunciation': {
      id: '/pronunciation'
      path: '/pronunciation'
      fullPath: '/pronunciation'
      preLoaderRoute: typeof PronunciationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$id': {
      id: '/brands/$id'
      path: '/brands/$id'
      fullPath: '/brands/$id'
      preLoaderRoute: typeof BrandsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$slug': {
      id: '/classes/$slug'
      path: '/classes/$slug'
      fullPath: '/classes/$slug'
      preLoaderRoute: typeof ClassesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturers/': {
      id: '/manufacturers/'
      path: '/manufacturers'
      fullPath: '/manufacturers/'
      preLoaderRoute: typeof ManufacturersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturers/$id': {
      id: '/manufacturers/$id'
      path: '/manufacturers/$id'
      fullPath: '/manufacturers/$id'
      preLoaderRoute: typeof ManufacturersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines/': {
      id: '/medicines/'
      path: '/medicines'
      fullPath: '/medicines/'
      preLoaderRoute: typeof MedicinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines/$slug': {
      id: '/medicines/$slug'
      path: '/medicines/$slug'
      fullPath: '/medicines/$slug'
      preLoaderRoute: typeof MedicinesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/manufacturers': {
      id: '/_authenticated/admin/manufacturers'
      path: '/admin/manufacturers'
      fullPath: '/admin/manufacturers'
      preLoaderRoute: typeof AuthenticatedAdminManufacturersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminManufacturersRoute: typeof AuthenticatedAdminManufacturersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminManufacturersRoute: AuthenticatedAdminManufacturersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdmeRoute: AdmeRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  DrugMemoryRoute: DrugMemoryRoute,
  FavoritesRoute: FavoritesRoute,
  FlashcardsRoute: FlashcardsRoute,
  LearnRoute: LearnRoute,
  LearningRoute: LearningRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  PronunciationRoute: PronunciationRoute,
  QuizRoute: QuizRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StudyRoute: StudyRoute,
  TermsRoute: TermsRoute,
  BrandsIdRoute: BrandsIdRoute,
  ClassesSlugRoute: ClassesSlugRoute,
  ManufacturersIdRoute: ManufacturersIdRoute,
  MedicinesSlugRoute: MedicinesSlugRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  ManufacturersIndexRoute: ManufacturersIndexRoute,
  MedicinesIndexRoute: MedicinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
