
INSERT INTO public.medicines (slug,generic_name,display_name,active_ingredient,salt,category,description,strengths,dosage_forms,routes,mechanism_of_action,pharmacodynamics,absorption,distribution,metabolism,excretion,bioavailability,half_life,protein_binding,onset,duration,indications,contraindications,warnings,common_adverse_effects,serious_adverse_effects,drug_interactions,monitoring,pregnancy,lactation,pediatric,geriatric,renal,hepatic,advantages,disadvantages,key_points,memory_trick,key_suffix,pronunciation_en,pronunciation_hi,last_verified) VALUES
('paracetamol','Paracetamol','Paracetamol (Acetaminophen)','Paracetamol','Paracetamol','Pain & Fever','A widely used analgesic and antipyretic with weak anti-inflammatory activity.',ARRAY['500 mg','650 mg','125 mg/5 mL'],ARRAY['Tablet','Syrup','Suppository','IV infusion'],ARRAY['Oral','Rectal','Intravenous'],'Mainly central inhibition of prostaglandin synthesis (COX pathway) and action on descending serotonergic pathways; exact mechanism not fully established.','Analgesic and antipyretic at therapeutic doses; minimal peripheral anti-inflammatory effect and no significant antiplatelet action.','Rapid and near-complete absorption from the small intestine after oral dosing.','Distributed widely into most body tissues and fluids.','Hepatic conjugation (glucuronidation, sulfation); a small fraction via CYP2E1 to the toxic metabolite NAPQI, normally detoxified by glutathione.','Renal excretion of conjugated metabolites.','Approximately 60-90% orally','About 2-3 hours in adults with normal hepatic function','Low (about 10-25%)','Around 30-60 minutes orally','4-6 hours',ARRAY['Mild to moderate pain','Fever'],ARRAY['Known hypersensitivity to paracetamol','Severe hepatocellular insufficiency'],ARRAY['Hepatotoxicity in overdose or with chronic excessive intake','Take care with multiple combination products that also contain paracetamol','Increased risk with chronic alcohol use or malnutrition'],ARRAY['Generally well tolerated at therapeutic doses','Nausea (uncommon)'],ARRAY['Acute liver failure in overdose','Rare severe skin reactions'],ARRAY['Warfarin (possible INR increase with sustained high-dose use)','Alcohol (increased hepatotoxicity risk)','Enzyme-inducing drugs'],ARRAY['Total daily dose from all sources','Liver function in prolonged or high-dose use'],'Commonly regarded as the analgesic/antipyretic of choice in pregnancy at the lowest effective dose for the shortest time; use under medical advice.','Considered compatible with breastfeeding in usual therapeutic doses.','Widely used in children with weight-based dosing determined by a clinician.','Usually well tolerated; consider hepatic status and total daily dose.','Dose interval may need extension in severe renal impairment.','Caution and dose reduction in hepatic impairment; avoid in severe hepatic disease.',ARRAY['Well tolerated at therapeutic doses','Suitable when NSAIDs are unsuitable','Available in many formulations'],ARRAY['Narrow safety margin in overdose','Little anti-inflammatory effect'],ARRAY['Antidote for overdose is N-acetylcysteine','Check combination cold/flu products for hidden paracetamol'],'"Para-SEE-ta-mol: pain and fever, but no swelling."','',E'pa-ra-SEE-ta-mol','पैरा-सी-टा-मोल',CURRENT_DATE),
('ibuprofen','Ibuprofen','Ibuprofen','Ibuprofen','Ibuprofen','Pain & Fever','A propionic acid NSAID with analgesic, antipyretic and anti-inflammatory activity.',ARRAY['200 mg','400 mg','600 mg','100 mg/5 mL'],ARRAY['Tablet','Suspension','Gel'],ARRAY['Oral','Topical'],'Non-selective reversible inhibition of COX-1 and COX-2, reducing prostaglandin synthesis.','Analgesic, antipyretic and anti-inflammatory; reversible inhibition of platelet aggregation.','Rapidly absorbed orally; food may delay peak concentration.','Extensively bound to plasma proteins; distributes into synovial fluid.','Hepatic oxidation (CYP2C9) and conjugation.','Renal excretion of metabolites.','High (over 80%)','About 2 hours','Approximately 99%','30-60 minutes','4-6 hours',ARRAY['Pain','Fever','Inflammatory conditions','Dysmenorrhoea'],ARRAY['Active peptic ulcer or GI bleeding','Severe heart failure','Severe renal impairment','NSAID or aspirin hypersensitivity','Third trimester of pregnancy'],ARRAY['Gastrointestinal bleeding and ulceration risk','Cardiovascular thrombotic risk with prolonged high-dose use','Renal impairment risk in dehydration'],ARRAY['Dyspepsia','Nausea','Abdominal discomfort','Dizziness'],ARRAY['Gastrointestinal bleeding','Acute kidney injury','Bronchospasm in susceptible asthmatics'],ARRAY['Anticoagulants (bleeding risk)','Other NSAIDs','ACE inhibitors/ARBs plus diuretics (triple whammy renal risk)','Lithium','Methotrexate'],ARRAY['Renal function','Blood pressure','Signs of GI bleeding'],'Avoid, particularly after 20 weeks and in the third trimester; use only under medical direction.','Small amounts pass into milk; generally considered compatible short term under medical advice.','Used in children with weight-based dosing determined by a clinician.','Higher risk of GI and renal adverse effects; use lowest effective dose.','Avoid in significant renal impairment.','Use with caution; avoid in severe hepatic impairment.',ARRAY['Anti-inflammatory in addition to analgesic effect','Effective for musculoskeletal pain'],ARRAY['Gastric irritation','Renal and cardiovascular cautions'],ARRAY['Take with or after food','Avoid combining with other NSAIDs'],'"-profen → NSAID family."','-profen',E'eye-byoo-PROH-fen','आई-बू-प्रो-फेन',CURRENT_DATE),
('diclofenac','Diclofenac','Diclofenac','Diclofenac','Diclofenac sodium / potassium','Pain & Fever','A potent NSAID used for musculoskeletal and inflammatory pain.',ARRAY['50 mg','75 mg','100 mg SR','1% gel'],ARRAY['Tablet','SR tablet','Injection','Gel'],ARRAY['Oral','Topical','Intramuscular'],'Preferential inhibition of cyclo-oxygenase enzymes, reducing prostaglandin synthesis.','Marked anti-inflammatory and analgesic activity.','Well absorbed orally; significant first-pass metabolism.','Highly protein bound; penetrates synovial fluid.','Hepatic metabolism (CYP2C9) with conjugation.','Renal and biliary excretion of metabolites.','Approximately 50% orally due to first-pass effect','About 1-2 hours','Over 99%','About 30 minutes (immediate release)','6-8 hours (formulation dependent)',ARRAY['Musculoskeletal pain','Arthritis','Post-operative pain'],ARRAY['Active peptic ulcer','Ischaemic heart disease and cerebrovascular disease','Severe heart failure','Severe renal impairment','NSAID hypersensitivity'],ARRAY['Higher cardiovascular thrombotic risk than some other NSAIDs','Gastrointestinal bleeding risk','Hepatotoxicity reported'],ARRAY['Dyspepsia','Nausea','Headache','Injection site pain'],ARRAY['GI bleeding','Myocardial infarction and stroke risk','Serious hepatic reactions'],ARRAY['Anticoagulants','Other NSAIDs','Corticosteroids','ACE inhibitors/ARBs and diuretics'],ARRAY['Liver function','Renal function','Blood pressure'],'Avoid, especially in the third trimester.','Generally avoided; seek medical advice.','Not generally recommended in young children.','Use with caution; prefer topical formulations where appropriate.','Avoid in significant renal impairment.','Avoid in hepatic impairment.',ARRAY['Potent anti-inflammatory effect','Topical option reduces systemic exposure'],ARRAY['Cardiovascular and GI risk','Hepatic monitoring may be needed'],ARRAY['Use lowest effective dose for shortest duration','Topical gel useful for localised pain'],'"-fenac → NSAID."','-fenac',E'dy-KLOE-fen-ak','डाइ-क्लो-फे-नैक',CURRENT_DATE),
('naproxen','Naproxen','Naproxen','Naproxen','Naproxen sodium','Pain & Fever','A longer-acting propionic acid NSAID.',ARRAY['250 mg','500 mg'],ARRAY['Tablet','Suspension'],ARRAY['Oral'],'Non-selective inhibition of COX-1 and COX-2.','Analgesic, antipyretic and anti-inflammatory with a longer duration than ibuprofen.','Well absorbed orally.','Highly protein bound.','Hepatic metabolism with demethylation and conjugation.','Predominantly renal.','Approximately 95%','About 12-17 hours','Over 99%','About 1 hour','Up to 12 hours',ARRAY['Arthritis','Musculoskeletal pain','Dysmenorrhoea','Acute gout'],ARRAY['Active peptic ulcer','Severe renal impairment','Severe heart failure','NSAID hypersensitivity'],ARRAY['GI bleeding risk','Fluid retention','Renal effects'],ARRAY['Dyspepsia','Heartburn','Headache','Dizziness'],ARRAY['GI bleeding','Renal impairment'],ARRAY['Anticoagulants','Other NSAIDs','Lithium','Methotrexate'],ARRAY['Renal function','Blood pressure','GI symptoms'],'Avoid, particularly in the third trimester.','Seek medical advice; generally other agents preferred.','Restricted use in children under medical supervision.','Use with caution due to long half-life.','Avoid in significant renal impairment.','Caution in hepatic impairment.',ARRAY['Twice-daily dosing','Long duration of action'],ARRAY['Long half-life increases exposure in the elderly'],ARRAY['Useful when longer NSAID cover is needed'],'"Naproxen = the long-acting -profen cousin."','-proxen',E'na-PROX-en','ना-प्रॉक-सेन',CURRENT_DATE),
('amoxicillin','Amoxicillin','Amoxicillin','Amoxicillin','Amoxicillin trihydrate','Antibiotics','An aminopenicillin beta-lactam antibiotic with broad activity.',ARRAY['250 mg','500 mg','125 mg/5 mL'],ARRAY['Capsule','Tablet','Dry syrup'],ARRAY['Oral'],'Inhibits bacterial cell wall synthesis by binding penicillin-binding proteins and blocking peptidoglycan cross-linking.','Time-dependent bactericidal activity.','Well absorbed orally and largely unaffected by food.','Distributes into most body fluids; poor CSF penetration unless meninges inflamed.','Limited hepatic metabolism.','Mainly renal excretion of unchanged drug.','Approximately 70-90%','About 1-1.5 hours','Approximately 20%','Within 1-2 hours','Dose-interval dependent (usually 8 hourly)',ARRAY['Respiratory tract infections','Otitis media','Urinary tract infection','Part of H. pylori eradication regimens'],ARRAY['Penicillin hypersensitivity'],ARRAY['Anaphylaxis risk in penicillin allergy','Rash if given in infectious mononucleosis','Antibiotic-associated diarrhoea and C. difficile risk'],ARRAY['Diarrhoea','Nausea','Rash'],ARRAY['Anaphylaxis','C. difficile colitis','Severe cutaneous reactions'],ARRAY['Methotrexate','Probenecid','Oral typhoid vaccine'],ARRAY['Signs of hypersensitivity','Renal function in prolonged therapy'],'Generally considered acceptable when clinically indicated; use under medical direction.','Considered compatible with breastfeeding.','Widely used in children with weight-based dosing.','Adjust dose in reduced renal function.','Dose reduction required in significant renal impairment.','No routine adjustment; monitor in hepatic disease.',ARRAY['Good oral absorption','Well established in children'],ARRAY['Inactivated by beta-lactamase producing organisms','Allergy risk'],ARRAY['Complete the prescribed course as directed','Not effective against viral illness'],'"-cillin → penicillin family, cell wall attack."','-cillin',E'a-mox-i-SIL-in','अमॉक्सी-सि-लिन',CURRENT_DATE),
('amoxicillin-clavulanic-acid','Amoxicillin + Clavulanic Acid','Amoxicillin + Clavulanic Acid (Co-amoxiclav)','Amoxicillin, Clavulanic acid','Amoxicillin trihydrate + Potassium clavulanate','Antibiotics','A fixed combination of amoxicillin with a beta-lactamase inhibitor.',ARRAY['500 mg + 125 mg','875 mg + 125 mg','200 mg + 28.5 mg/5 mL'],ARRAY['Tablet','Dry syrup','Injection'],ARRAY['Oral','Intravenous'],'Amoxicillin inhibits cell wall synthesis while clavulanic acid irreversibly inhibits many bacterial beta-lactamases, protecting amoxicillin from degradation.','Extends the antibacterial spectrum to many beta-lactamase producing organisms.','Both components are well absorbed orally; taking with food improves tolerance.','Distributes into body fluids similarly to amoxicillin.','Clavulanic acid undergoes more extensive metabolism than amoxicillin.','Predominantly renal.','Amoxicillin approximately 70-90%; clavulanate somewhat lower','About 1 hour for both components','Low for both components','Within 1-2 hours','8-12 hourly dosing depending on formulation',ARRAY['Respiratory infections with suspected resistant organisms','Sinusitis','Otitis media','Skin and soft tissue infection','Animal bite prophylaxis'],ARRAY['Penicillin hypersensitivity','Previous co-amoxiclav associated jaundice or hepatic dysfunction'],ARRAY['Cholestatic jaundice risk, more common in older adults and prolonged courses','Diarrhoea more frequent than with amoxicillin alone'],ARRAY['Diarrhoea','Nausea','Rash'],ARRAY['Cholestatic hepatitis','Anaphylaxis','C. difficile colitis'],ARRAY['Methotrexate','Warfarin (INR changes reported)','Probenecid'],ARRAY['Liver function in prolonged courses','Signs of hypersensitivity'],'Use only when clearly indicated under medical direction.','Considered compatible; monitor infant for GI upset.','Used in children with weight-based dosing.','Higher risk of hepatic adverse effects; use with care.','Dose adjustment in renal impairment.','Avoid in previous co-amoxiclav related hepatic injury.',ARRAY['Covers many beta-lactamase producing bacteria'],ARRAY['More GI upset than plain amoxicillin','Cholestatic jaundice risk'],ARRAY['Take with food to reduce GI upset','Reserve for situations where the broader cover is needed'],'"Clavulanic acid = the bodyguard protecting amoxicillin."','-cillin',E'a-mox-i-SIL-in plus klav-yoo-LAN-ik','अमॉक्सी-सि-लिन + क्लैवु-लैनिक ऐसिड',CURRENT_DATE),
('azithromycin','Azithromycin','Azithromycin','Azithromycin','Azithromycin dihydrate','Antibiotics','A macrolide (azalide) antibiotic with a long tissue half-life.',ARRAY['250 mg','500 mg','200 mg/5 mL'],ARRAY['Tablet','Dry syrup','Injection'],ARRAY['Oral','Intravenous'],'Binds the 50S bacterial ribosomal subunit and inhibits protein synthesis.','Predominantly bacteriostatic with extensive tissue accumulation.','Absorbed orally; food reduces absorption of some formulations.','Very large volume of distribution with high intracellular and tissue concentrations.','Limited hepatic metabolism.','Mainly biliary excretion with a small renal component.','Approximately 37%','Terminal half-life about 68 hours','Variable, low to moderate','Within hours','Sustained tissue levels allow short courses',ARRAY['Community-acquired pneumonia','Pharyngitis in penicillin allergy','Certain sexually transmitted infections','Enteric fever (as directed)'],ARRAY['Macrolide hypersensitivity','History of cholestatic jaundice with azithromycin'],ARRAY['QT interval prolongation risk','Hepatic dysfunction reported','Antimicrobial resistance with inappropriate use'],ARRAY['Nausea','Abdominal pain','Diarrhoea'],ARRAY['QT prolongation and arrhythmia','Severe hepatic reactions','Severe cutaneous reactions'],ARRAY['Other QT-prolonging drugs','Antacids (reduce absorption of some forms)','Warfarin (monitor INR)'],ARRAY['ECG in patients at QT risk','Liver function if prolonged use'],'Use only when clearly indicated under medical direction.','Considered compatible under medical advice.','Used in children with weight-based dosing.','Consider cardiac comorbidity and QT risk.','No routine adjustment in mild impairment; caution in severe.','Avoid in significant hepatic impairment.',ARRAY['Short courses due to long tissue half-life','Alternative in penicillin allergy'],ARRAY['Growing resistance','QT prolongation risk'],ARRAY['Do not use for ordinary viral colds','Complete the prescribed course as directed'],'"-thromycin → macrolide, 50S ribosome."','-thromycin',E'az-ith-roe-MY-sin','अज़िथ्रो-माय-सिन',CURRENT_DATE),
('doxycycline','Doxycycline','Doxycycline','Doxycycline','Doxycycline hyclate / monohydrate','Antibiotics','A broad-spectrum tetracycline antibiotic.',ARRAY['100 mg'],ARRAY['Capsule','Tablet'],ARRAY['Oral'],'Binds the 30S ribosomal subunit and blocks attachment of aminoacyl-tRNA, inhibiting protein synthesis.','Bacteriostatic with broad spectrum including atypical and rickettsial organisms.','Well absorbed orally; absorption reduced by divalent and trivalent cations.','Widely distributed and lipophilic.','Limited hepatic metabolism.','Substantial faecal excretion plus renal elimination.','Approximately 90%','About 18-22 hours','Around 80-90%','Within hours','Once or twice daily dosing',ARRAY['Atypical pneumonia','Acne','Scrub typhus and rickettsial infections','Malaria prophylaxis (as directed)'],ARRAY['Pregnancy','Children generally under 8 years','Tetracycline hypersensitivity'],ARRAY['Photosensitivity','Oesophageal irritation and ulceration if taken without water','Tooth discolouration in young children'],ARRAY['Nausea','Photosensitivity','Oesophageal irritation'],ARRAY['Severe oesophageal ulceration','Intracranial hypertension (rare)'],ARRAY['Antacids and iron/calcium (reduced absorption)','Warfarin','Retinoids'],ARRAY['Response to therapy','Signs of photosensitivity'],'Contraindicated in pregnancy.','Generally avoided; seek medical advice.','Generally avoided under 8 years except in specific serious infections.','Usually well tolerated.','No routine adjustment needed.','Caution in hepatic impairment.',ARRAY['Good oral bioavailability','Useful in atypical and rickettsial infections'],ARRAY['Photosensitivity','Not for pregnancy or young children'],ARRAY['Take with a full glass of water and remain upright','Use sun protection'],'"-cycline → 30S ribosome; avoid in pregnancy and small children."','-cycline',E'dox-i-SY-kleen','डॉक्सी-साइ-क्लीन',CURRENT_DATE),
('cefixime','Cefixime','Cefixime','Cefixime','Cefixime trihydrate','Antibiotics','A third-generation oral cephalosporin.',ARRAY['200 mg','400 mg','50 mg/5 mL'],ARRAY['Tablet','Dry syrup'],ARRAY['Oral'],'Inhibits bacterial cell wall synthesis by binding penicillin-binding proteins.','Bactericidal with useful gram-negative activity.','Absorbed orally with moderate bioavailability.','Distributes into body fluids.','Minimal hepatic metabolism.','Renal and biliary excretion.','Approximately 40-50%','About 3-4 hours','Approximately 65%','Within hours','12-24 hourly dosing',ARRAY['Urinary tract infection','Otitis media','Pharyngitis and tonsillitis','Enteric fever (as directed)'],ARRAY['Cephalosporin hypersensitivity','Severe penicillin anaphylaxis (caution)'],ARRAY['Cross-reactivity with penicillin allergy','C. difficile associated diarrhoea'],ARRAY['Diarrhoea','Abdominal pain','Nausea'],ARRAY['Anaphylaxis','C. difficile colitis'],ARRAY['Probenecid','Anticoagulants (monitor)'],ARRAY['Renal function','Signs of hypersensitivity'],'Use only when clearly indicated under medical direction.','Considered compatible under medical advice.','Widely used in children with weight-based dosing.','Adjust for renal function.','Dose reduction in significant renal impairment.','No routine adjustment.',ARRAY['Oral third-generation cephalosporin','Convenient dosing'],ARRAY['Overuse contributes to resistance'],ARRAY['Reserve for appropriate indications'],'"Cef- → cephalosporin, a beta-lactam."','cef-',E'se-FIX-eem','सी-फिक्-सीम',CURRENT_DATE),
('ceftriaxone','Ceftriaxone','Ceftriaxone','Ceftriaxone','Ceftriaxone sodium','Antibiotics','A parenteral third-generation cephalosporin used for serious infections.',ARRAY['250 mg','500 mg','1 g','2 g'],ARRAY['Injection'],ARRAY['Intravenous','Intramuscular'],'Inhibits bacterial cell wall synthesis via penicillin-binding protein binding.','Bactericidal with broad gram-negative cover and good CSF penetration.','Not absorbed orally; given parenterally.','Wide distribution including cerebrospinal fluid when meninges are inflamed.','Minimal metabolism.','Dual renal and biliary elimination.','100% by the parenteral route','About 6-9 hours','Approximately 85-95%','Within 1-2 hours','Once-daily dosing in most indications',ARRAY['Pneumonia','Meningitis','Enteric fever','Serious intra-abdominal and urinary infections'],ARRAY['Cephalosporin hypersensitivity','Neonates with hyperbilirubinaemia','Concurrent calcium-containing IV solutions in neonates'],ARRAY['Biliary pseudolithiasis','Do not mix with calcium-containing solutions in neonates','C. difficile risk'],ARRAY['Injection site reactions','Diarrhoea','Rash'],ARRAY['Anaphylaxis','Haemolytic anaemia (rare)','C. difficile colitis'],ARRAY['Calcium-containing IV solutions','Anticoagulants'],ARRAY['Renal and hepatic function','Signs of hypersensitivity'],'Used when clearly indicated under medical direction.','Considered compatible under medical advice.','Used in children including neonates with specific restrictions.','Generally well tolerated; monitor renal function.','Adjust in combined severe renal and hepatic impairment.','Adjust in combined severe renal and hepatic impairment.',ARRAY['Once-daily dosing','Good CSF penetration'],ARRAY['Parenteral only','Biliary sludging'],ARRAY['Hospital and clinic use under supervision'],'"Ceftriaxone = once-daily heavyweight cephalosporin."','cef-',E'sef-try-AX-one','सेफ्-ट्राइ-ऐक्-सोन',CURRENT_DATE),
('metronidazole','Metronidazole','Metronidazole','Metronidazole','Metronidazole','Antibiotics','A nitroimidazole active against anaerobic bacteria and several protozoa.',ARRAY['200 mg','400 mg','500 mg IV'],ARRAY['Tablet','Suspension','Injection','Gel'],ARRAY['Oral','Intravenous','Topical'],'Reduced within anaerobic organisms to reactive intermediates that damage microbial DNA.','Bactericidal against anaerobes and amoebicidal.','Well absorbed orally.','Widely distributed including CSF, bone and abscesses.','Hepatic metabolism.','Mainly renal excretion of metabolites.','Approximately 90-100% orally','About 8 hours','Under 20%','Within 1-2 hours','8-12 hourly dosing',ARRAY['Amoebiasis','Giardiasis','Bacterial vaginosis','Anaerobic bacterial infections'],ARRAY['Known hypersensitivity','First trimester of pregnancy for high-dose regimens (as advised)'],ARRAY['Avoid alcohol during and for at least 48 hours after therapy (disulfiram-like reaction)','Peripheral neuropathy with prolonged use'],ARRAY['Metallic taste','Nausea','Dark urine','Headache'],ARRAY['Peripheral neuropathy','Seizures (rare)','Encephalopathy (rare)'],ARRAY['Alcohol','Warfarin','Lithium','Phenytoin'],ARRAY['Neurological symptoms in prolonged courses','Full blood count in long therapy'],'Use only when clearly indicated; follow medical advice regarding trimester and dose.','Seek medical advice; high single doses may require temporary interruption.','Used in children with weight-based dosing.','Generally well tolerated.','No routine adjustment in mild impairment.','Dose reduction in severe hepatic impairment.',ARRAY['Excellent anaerobic and protozoal cover','Good tissue penetration'],ARRAY['Alcohol interaction','Taste disturbance'],ARRAY['Strictly avoid alcohol','Complete the course as directed'],'"-nidazole → anaerobes and amoebae; no alcohol."','-nidazole',E'met-roe-NYE-da-zole','मेट्रो-नाइ-डा-ज़ोल',CURRENT_DATE),
('omeprazole','Omeprazole','Omeprazole','Omeprazole','Omeprazole','Acidity & GERD','A proton pump inhibitor that suppresses gastric acid secretion.',ARRAY['20 mg','40 mg'],ARRAY['Capsule','Tablet','Injection'],ARRAY['Oral','Intravenous'],'Irreversibly inhibits the gastric H+/K+-ATPase (proton pump) in parietal cells.','Profound and prolonged suppression of both basal and stimulated acid secretion.','Acid-labile; given as enteric-coated formulation, absorbed in the small intestine.','Highly protein bound; concentrates in parietal cells.','Hepatic metabolism via CYP2C19 and CYP3A4.','Mainly renal excretion of metabolites.','Approximately 35-60%, increasing with repeated dosing','About 0.5-1 hour in plasma, but effect lasts far longer','Approximately 95%','Within 1 hour','Acid suppression persists up to 72 hours',ARRAY['GERD','Peptic ulcer disease','H. pylori eradication regimens','NSAID ulcer prophylaxis'],ARRAY['Hypersensitivity to PPIs','Concomitant use with certain antiretrovirals'],ARRAY['May mask symptoms of gastric malignancy','Long-term use associated with hypomagnesaemia, B12 deficiency and fracture risk','Reduces clopidogrel activation via CYP2C19'],ARRAY['Headache','Diarrhoea','Abdominal pain','Nausea'],ARRAY['C. difficile associated diarrhoea','Severe hypomagnesaemia','Acute interstitial nephritis (rare)'],ARRAY['Clopidogrel','Ketoconazole and itraconazole','Methotrexate','Digoxin'],ARRAY['Magnesium and B12 in long-term therapy','Ongoing need for therapy'],'Use when clearly indicated under medical direction.','Considered compatible under medical advice.','Used in children under specialist direction.','Reassess long-term need regularly.','No routine adjustment.','Dose reduction in severe hepatic impairment.',ARRAY['Potent, long-lasting acid suppression','Once-daily dosing'],ARRAY['CYP2C19 interactions including clopidogrel','Long-term use risks'],ARRAY['Take 30-60 minutes before food','Review long-term need periodically'],'"-prazole → proton pump inhibitor."','-prazole',E'oh-MEP-ra-zole','ओ-मेप्रा-ज़ोल',CURRENT_DATE),
('pantoprazole','Pantoprazole','Pantoprazole','Pantoprazole','Pantoprazole sodium','Acidity & GERD','A proton pump inhibitor with fewer CYP-mediated interactions than omeprazole.',ARRAY['20 mg','40 mg'],ARRAY['Tablet','Injection'],ARRAY['Oral','Intravenous'],'Irreversibly inhibits the gastric H+/K+-ATPase in parietal cells.','Sustained suppression of gastric acid secretion.','Enteric-coated for absorption in the small intestine.','Highly protein bound.','Hepatic metabolism via CYP2C19 with sulfate conjugation.','Renal excretion of metabolites.','Approximately 77%','About 1 hour in plasma with far longer pharmacological effect','Approximately 98%','Within 1 hour','24 hours of acid control with regular dosing',ARRAY['GERD','Erosive oesophagitis','Peptic ulcer','Stress ulcer prophylaxis (as directed)'],ARRAY['Hypersensitivity to PPIs'],ARRAY['May mask gastric malignancy','Long-term use risks similar to other PPIs'],ARRAY['Headache','Diarrhoea','Nausea','Flatulence'],ARRAY['Severe hypomagnesaemia','Acute interstitial nephritis (rare)'],ARRAY['Methotrexate','Atazanavir','Ketoconazole'],ARRAY['Magnesium in long-term therapy','Ongoing need'],'Use when clearly indicated under medical direction.','Considered compatible under medical advice.','Used in children under specialist direction.','Generally well tolerated.','No routine adjustment.','Reduce dose in severe hepatic impairment.',ARRAY['Fewer significant CYP interactions than omeprazole','IV option available'],ARRAY['Same long-term PPI considerations'],ARRAY['Take before breakfast'],'"-prazole → pump blocker; pantoprazole = fewer interactions."','-prazole',E'pan-TOE-pra-zole','पैन्टो-प्रा-ज़ोल',CURRENT_DATE),
('ondansetron','Ondansetron','Ondansetron','Ondansetron','Ondansetron hydrochloride','Vomiting & Nausea','A selective 5-HT3 receptor antagonist antiemetic.',ARRAY['4 mg','8 mg'],ARRAY['Tablet','Mouth dissolving tablet','Injection','Syrup'],ARRAY['Oral','Intravenous','Intramuscular'],'Selectively blocks serotonin 5-HT3 receptors peripherally on vagal afferents and centrally in the chemoreceptor trigger zone.','Prevents and treats nausea and vomiting without significant dopaminergic effects.','Well absorbed orally with first-pass metabolism.','Moderate volume of distribution.','Extensive hepatic metabolism (CYP3A4, CYP2D6, CYP1A2).','Renal excretion of metabolites.','Approximately 60%','About 3-6 hours','Approximately 70-76%','Within 30 minutes','Around 8-12 hours',ARRAY['Chemotherapy-induced nausea and vomiting','Radiotherapy-induced vomiting','Post-operative nausea and vomiting'],ARRAY['Concomitant apomorphine','Known hypersensitivity','Congenital long QT syndrome'],ARRAY['Dose-dependent QT prolongation','Serotonin syndrome when combined with other serotonergic drugs','Constipation'],ARRAY['Headache','Constipation','Fatigue'],ARRAY['QT prolongation and torsades de pointes','Serotonin syndrome'],ARRAY['Apomorphine','Other QT-prolonging drugs','SSRIs and SNRIs','Tramadol'],ARRAY['ECG in cardiac risk patients','Electrolytes'],'Use only when clearly indicated under medical direction.','Seek medical advice.','Used in children under medical supervision.','Consider cardiac status and QT risk.','No routine adjustment.','Maximum daily dose reduced in severe hepatic impairment.',ARRAY['Highly effective antiemetic','Mouth-dissolving option'],ARRAY['QT prolongation','Constipation'],ARRAY['Not a treatment for the underlying cause of vomiting'],'"-setron → 5-HT3 blocker."','-setron',E'on-DAN-se-tron','ऑन-डैन-सी-ट्रॉन',CURRENT_DATE),
('cetirizine','Cetirizine','Cetirizine','Cetirizine','Cetirizine dihydrochloride','Allergy','A second-generation H1 antihistamine.',ARRAY['5 mg','10 mg','5 mg/5 mL'],ARRAY['Tablet','Syrup','Drops'],ARRAY['Oral'],'Selectively antagonises peripheral histamine H1 receptors.','Relieves allergic symptoms with limited central penetration, though some sedation occurs.','Rapidly and well absorbed orally.','Limited distribution; low CNS penetration relative to first-generation agents.','Minimal hepatic metabolism.','Largely renal excretion of unchanged drug.','Approximately 70% or more','About 8-9 hours in adults','Approximately 93%','Within 1 hour','24 hours',ARRAY['Allergic rhinitis','Chronic urticaria','Allergic conjunctivitis','Pruritus'],ARRAY['Known hypersensitivity','Severe renal impairment (dose adjustment needed)'],ARRAY['May cause drowsiness; caution with driving','Additive sedation with alcohol or CNS depressants'],ARRAY['Drowsiness','Dry mouth','Fatigue','Headache'],ARRAY['Rare hypersensitivity reactions'],ARRAY['Alcohol','CNS depressants','Theophylline (minor)'],ARRAY['Symptom control','Sedation level'],'Use only if clearly needed under medical advice.','Passes into breast milk; seek medical advice.','Used in children with age-appropriate dosing.','Reduce dose with reduced renal function.','Dose reduction in renal impairment.','Caution in hepatic impairment.',ARRAY['Once-daily dosing','Less sedating than first-generation agents'],ARRAY['Can still cause drowsiness in some people'],ARRAY['Take in the evening if drowsiness occurs'],'"Cetirizine = allergy once a day."','-zine',E'se-TEER-i-zeen','सेटी-रि-ज़ीन',CURRENT_DATE),
('loratadine','Loratadine','Loratadine','Loratadine','Loratadine','Allergy','A non-sedating second-generation H1 antihistamine.',ARRAY['10 mg','5 mg/5 mL'],ARRAY['Tablet','Syrup'],ARRAY['Oral'],'Selective peripheral H1 receptor antagonism.','Long-acting antihistamine effect with minimal sedation at usual doses.','Rapidly absorbed orally.','Highly protein bound; poor CNS penetration.','Extensive hepatic metabolism (CYP3A4/CYP2D6) to active desloratadine.','Renal and biliary excretion.','High but subject to first-pass metabolism','About 8-11 hours (active metabolite longer)','Approximately 97%','1-3 hours','24 hours',ARRAY['Allergic rhinitis','Chronic urticaria'],ARRAY['Known hypersensitivity'],ARRAY['Caution in severe hepatic impairment','Rarely sedating but individual variation exists'],ARRAY['Headache','Dry mouth','Fatigue'],ARRAY['Rare hypersensitivity reactions'],ARRAY['Ketoconazole','Erythromycin','Cimetidine'],ARRAY['Symptom control'],'Use only if clearly needed under medical advice.','Seek medical advice.','Used in children with age-appropriate dosing.','Generally well tolerated.','Extend dosing interval in significant renal impairment.','Reduce dose in hepatic impairment.',ARRAY['Minimal sedation','Once-daily dosing'],ARRAY['Slower onset than some alternatives'],ARRAY['Preferred where daytime alertness is important'],'"-tadine → antihistamine."','-tadine',E'lor-AT-a-deen','लॉरा-टा-डीन',CURRENT_DATE),
('salbutamol','Salbutamol','Salbutamol (Albuterol)','Salbutamol','Salbutamol sulphate','Asthma & COPD','A short-acting beta-2 agonist bronchodilator.',ARRAY['100 mcg/puff','2 mg','2.5 mg respule'],ARRAY['Inhaler','Nebuliser solution','Tablet','Syrup'],ARRAY['Inhalation','Oral','Intravenous'],'Selectively stimulates beta-2 adrenoceptors, increasing intracellular cAMP and relaxing bronchial smooth muscle.','Rapid bronchodilation; higher doses may cause beta-1 effects such as tachycardia.','Rapid onset after inhalation; oral absorption slower with first-pass metabolism.','Limited systemic distribution after inhalation.','Hepatic metabolism by sulfation.','Renal excretion.','Inhaled route delivers a small fraction to the lungs with high local effect','About 4-6 hours','Approximately 10%','Within 5 minutes when inhaled','4-6 hours',ARRAY['Acute bronchospasm in asthma','COPD symptom relief','Exercise-induced bronchospasm'],ARRAY['Known hypersensitivity'],ARRAY['Increasing reliever use indicates poorly controlled asthma','Hypokalaemia with high doses','Caution in cardiac disease and thyrotoxicosis'],ARRAY['Tremor','Palpitations','Headache','Muscle cramps'],ARRAY['Severe hypokalaemia','Paradoxical bronchospasm','Cardiac arrhythmia at high doses'],ARRAY['Non-selective beta blockers (antagonism)','Diuretics (hypokalaemia)','Digoxin'],ARRAY['Inhaler technique','Frequency of reliever use','Serum potassium with high-dose therapy'],'Considered acceptable when needed for asthma control under medical direction.','Considered compatible with breastfeeding.','Widely used in children with spacer devices.','Caution with cardiac comorbidity.','No routine adjustment.','No routine adjustment.',ARRAY['Rapid symptom relief','Inhaled route limits systemic effects'],ARRAY['No anti-inflammatory action','Overuse masks deteriorating control'],ARRAY['Use a spacer for better lung delivery','Frequent use should prompt medical review'],'"-terol / salbutamol → beta-2 opens the airways."','-terol',E'sal-BYOO-ta-mol','सैल्-ब्यू-टा-मोल',CURRENT_DATE),
('metformin','Metformin','Metformin','Metformin','Metformin hydrochloride','Diabetes','A biguanide and usual first-line oral therapy for type 2 diabetes.',ARRAY['500 mg','850 mg','1000 mg','500 mg SR'],ARRAY['Tablet','SR tablet'],ARRAY['Oral'],'Reduces hepatic gluconeogenesis, decreases intestinal glucose absorption and improves peripheral insulin sensitivity, partly through AMP-activated protein kinase pathways.','Lowers fasting and postprandial glucose without stimulating insulin secretion, so it does not intrinsically cause hypoglycaemia.','Slow and incomplete absorption from the small intestine.','Low protein binding; accumulates in intestinal wall and erythrocytes.','Not metabolised.','Excreted unchanged by the kidneys via tubular secretion.','Approximately 50-60%','About 4-9 hours (plasma)','Negligible','Days for full glycaemic effect','Depends on formulation; SR is once daily',ARRAY['Type 2 diabetes mellitus','Polycystic ovary syndrome (as directed)','Prediabetes in selected patients'],ARRAY['eGFR below 30 mL/min/1.73 m2','Acute metabolic acidosis','Severe dehydration or hypoxic states'],ARRAY['Rare but serious lactic acidosis, mainly with renal impairment','Withhold around iodinated contrast procedures and major surgery','Long-term use may reduce vitamin B12'],ARRAY['Nausea','Diarrhoea','Metallic taste','Abdominal discomfort'],ARRAY['Lactic acidosis (rare)','Symptomatic B12 deficiency'],ARRAY['Iodinated contrast media','Alcohol','Diuretics and NSAIDs during dehydration','Cimetidine'],ARRAY['Renal function at least annually','HbA1c','Vitamin B12 in long-term use'],'Often continued or used in pregnancy under specialist direction; follow medical advice.','Considered compatible under medical advice.','Used in older children with type 2 diabetes under specialist care.','Check renal function before and during therapy.','Dose limited below eGFR 45; contraindicated below 30.','Avoid in significant hepatic impairment due to lactic acidosis risk.',ARRAY['Weight neutral','No intrinsic hypoglycaemia','Strong long-term evidence','Low cost'],ARRAY['GI intolerance at start','Renal restrictions'],ARRAY['Start low and increase slowly with food','SR formulation improves GI tolerance'],'"Metformin = first-line, no hypo by itself."','',E'met-FOR-min','मेट-फॉर-मिन',CURRENT_DATE),
('glimepiride','Glimepiride','Glimepiride','Glimepiride','Glimepiride','Diabetes','A second-generation sulfonylurea insulin secretagogue.',ARRAY['1 mg','2 mg','3 mg','4 mg'],ARRAY['Tablet'],ARRAY['Oral'],'Closes ATP-sensitive potassium channels on pancreatic beta cells, causing depolarisation, calcium entry and insulin release.','Lowers blood glucose by increasing endogenous insulin secretion; requires functioning beta cells.','Completely absorbed orally.','Small volume of distribution; highly protein bound.','Hepatic metabolism via CYP2C9 to metabolites with some activity.','Renal and faecal excretion.','Essentially complete','About 5-8 hours','Over 99%','Within 1 hour','Up to 24 hours',ARRAY['Type 2 diabetes mellitus when metformin alone is insufficient'],ARRAY['Type 1 diabetes','Diabetic ketoacidosis','Severe hepatic or renal impairment','Sulfonylurea hypersensitivity'],ARRAY['Hypoglycaemia risk, particularly if meals are missed','Weight gain','Caution in the elderly and in renal impairment'],ARRAY['Hypoglycaemia','Weight gain','Nausea'],ARRAY['Severe prolonged hypoglycaemia'],ARRAY['Other glucose-lowering drugs','Beta blockers (mask hypoglycaemia)','Fluconazole','Alcohol'],ARRAY['Blood glucose','HbA1c','Hypoglycaemia symptoms','Weight'],'Generally avoided; insulin is usually preferred in pregnancy.','Generally avoided.','Not usually used in children.','Higher hypoglycaemia risk; start at the lowest dose.','Reduce dose; avoid in severe impairment.','Avoid in significant hepatic impairment.',ARRAY['Effective glucose lowering','Once-daily dosing','Low cost'],ARRAY['Hypoglycaemia','Weight gain'],ARRAY['Take with breakfast','Never skip meals while on therapy'],'"gli- → sulfonylurea; can cause hypos."','gli-',E'glye-MEP-i-ride','ग्लाइ-मे-पि-राइड',CURRENT_DATE),
('amlodipine','Amlodipine','Amlodipine','Amlodipine','Amlodipine besylate','Blood Pressure','A long-acting dihydropyridine calcium channel blocker.',ARRAY['2.5 mg','5 mg','10 mg'],ARRAY['Tablet'],ARRAY['Oral'],'Blocks L-type calcium channels in vascular smooth muscle, causing peripheral arterial vasodilation.','Reduces peripheral vascular resistance and blood pressure with minimal negative inotropic effect at usual doses.','Slowly and well absorbed orally, unaffected by food.','Large volume of distribution; highly protein bound.','Extensive hepatic metabolism via CYP3A4.','Renal excretion of metabolites.','Approximately 64-90%','About 30-50 hours','Approximately 93%','Gradual over 6-12 hours','Over 24 hours',ARRAY['Hypertension','Chronic stable angina','Vasospastic angina'],ARRAY['Cardiogenic shock','Severe aortic stenosis','Known hypersensitivity'],ARRAY['Dose-dependent ankle oedema','Caution in severe hepatic impairment','Reflex tachycardia is uncommon due to slow onset'],ARRAY['Ankle oedema','Flushing','Headache','Palpitations'],ARRAY['Severe hypotension','Rarely worsening angina on initiation'],ARRAY['Simvastatin (dose limit)','CYP3A4 inhibitors such as clarithromycin','Grapefruit juice'],ARRAY['Blood pressure','Ankle oedema','Heart rate'],'Not first choice; use only under specialist direction.','Seek medical advice.','Used in children under specialist direction.','Effective and generally well tolerated; start low.','No routine adjustment.','Start low and titrate slowly in hepatic impairment.',ARRAY['Once-daily dosing','Smooth 24-hour blood pressure control','Effective in many Indian patients'],ARRAY['Ankle oedema is a common reason for discontinuation'],ARRAY['Oedema is dose related and not usually due to fluid overload'],'"-dipine → dihydropyridine CCB, ankle oedema clue."','-dipine',E'am-LOE-di-peen','ऐम्-लो-डि-पीन',CURRENT_DATE),
('losartan','Losartan','Losartan','Losartan','Losartan potassium','Blood Pressure','The first angiotensin II receptor blocker in clinical use.',ARRAY['25 mg','50 mg','100 mg'],ARRAY['Tablet'],ARRAY['Oral'],'Selectively blocks the angiotensin II type 1 (AT1) receptor, preventing angiotensin II mediated vasoconstriction and aldosterone release.','Lowers blood pressure and reduces intraglomerular pressure; also has a mild uricosuric effect.','Well absorbed orally with significant first-pass metabolism.','Highly protein bound; does not readily cross the blood-brain barrier.','Hepatic metabolism via CYP2C9 and CYP3A4 to the more potent active metabolite E-3174.','Renal and biliary excretion.','Approximately 33%','Losartan about 2 hours; active metabolite 6-9 hours','Over 98%','Within 6 hours','24 hours',ARRAY['Hypertension','Diabetic nephropathy with proteinuria','Left ventricular hypertrophy risk reduction'],ARRAY['Pregnancy','Bilateral renal artery stenosis','Concomitant aliskiren in diabetes'],ARRAY['Hyperkalaemia','Renal function decline in volume depletion','Symptomatic hypotension after the first dose in volume-depleted patients'],ARRAY['Dizziness','Fatigue','Hyperkalaemia'],ARRAY['Angioedema (rare)','Acute kidney injury','Severe hyperkalaemia'],ARRAY['Potassium supplements and potassium-sparing diuretics','NSAIDs','Lithium','ACE inhibitors (avoid dual blockade)'],ARRAY['Serum potassium','Renal function','Blood pressure'],'Contraindicated in pregnancy due to fetal renal toxicity.','Generally avoided; alternatives preferred.','Used in children over 6 years under specialist direction.','Effective; monitor renal function and potassium.','Monitor closely; avoid in bilateral renal artery stenosis.','Reduce initial dose in hepatic impairment.',ARRAY['Well tolerated','No ACE inhibitor cough','Mild uricosuric effect'],ARRAY['Contraindicated in pregnancy','Hyperkalaemia risk'],ARRAY['Check potassium and creatinine after initiation','Do not combine with an ACE inhibitor'],'"-sartan → ARB; -pril → ACE inhibitor."','-sartan',E'loe-SAR-tan','लो-सार्-टन',CURRENT_DATE),
('telmisartan','Telmisartan','Telmisartan','Telmisartan','Telmisartan','Blood Pressure','A long-acting angiotensin II receptor blocker.',ARRAY['20 mg','40 mg','80 mg'],ARRAY['Tablet'],ARRAY['Oral'],'Selective AT1 receptor antagonism with partial PPAR-gamma agonist activity.','Provides sustained 24-hour blood pressure reduction.','Absorbed rapidly with variable bioavailability.','Very high protein binding and a large volume of distribution.','Minimal metabolism; conjugated to an inactive glucuronide.','Almost entirely faecal (biliary) excretion.','Approximately 42-58%','About 24 hours','Over 99%','Within a few hours; full effect over weeks','Beyond 24 hours',ARRAY['Hypertension','Cardiovascular risk reduction in selected patients'],ARRAY['Pregnancy','Biliary obstruction','Severe hepatic impairment'],ARRAY['Hyperkalaemia','Hypotension in volume depletion','Renal function changes'],ARRAY['Dizziness','Back pain','Sinus symptoms'],ARRAY['Angioedema (rare)','Acute kidney injury','Hyperkalaemia'],ARRAY['Potassium-sparing agents','NSAIDs','Digoxin','Lithium'],ARRAY['Potassium','Renal function','Blood pressure'],'Contraindicated in pregnancy.','Generally avoided.','Not recommended in children.','Effective and generally well tolerated.','No routine adjustment in mild to moderate impairment.','Contraindicated in severe hepatic impairment and biliary obstruction.',ARRAY['Longest half-life among ARBs','Good early-morning blood pressure control'],ARRAY['Contraindicated in pregnancy and biliary obstruction'],ARRAY['Eliminated mainly by the liver, unlike losartan'],'"Telmisartan = the longest-acting -sartan."','-sartan',E'tel-mi-SAR-tan','टेल्-मि-सार्-टन',CURRENT_DATE),
('atorvastatin','Atorvastatin','Atorvastatin','Atorvastatin','Atorvastatin calcium','Cholesterol','A potent HMG-CoA reductase inhibitor.',ARRAY['10 mg','20 mg','40 mg','80 mg'],ARRAY['Tablet'],ARRAY['Oral'],'Competitively inhibits HMG-CoA reductase, the rate-limiting enzyme of hepatic cholesterol synthesis, upregulating LDL receptors.','Lowers LDL cholesterol and triglycerides, modestly raises HDL, and has plaque-stabilising effects.','Rapidly absorbed with extensive first-pass metabolism.','Highly protein bound; hepatoselective.','Extensive hepatic metabolism via CYP3A4 to active metabolites.','Mainly biliary excretion.','Approximately 14% systemically but high hepatic extraction','Parent drug about 14 hours; active metabolites longer','Over 98%','Lipid effects over 2 weeks','Suitable for once-daily dosing at any time of day',ARRAY['Primary and secondary prevention of cardiovascular disease','Hypercholesterolaemia','Mixed dyslipidaemia'],ARRAY['Active liver disease','Unexplained persistent transaminase elevation','Pregnancy and breastfeeding'],ARRAY['Myopathy and rarely rhabdomyolysis','Interaction with strong CYP3A4 inhibitors','Small increase in new-onset diabetes'],ARRAY['Myalgia','Headache','Gastrointestinal upset','Raised transaminases'],ARRAY['Rhabdomyolysis','Immune-mediated necrotising myopathy (rare)','Severe hepatic injury (rare)'],ARRAY['Clarithromycin and other strong CYP3A4 inhibitors','Fibrates (especially gemfibrozil)','Ciclosporin','Grapefruit juice in large amounts'],ARRAY['Lipid profile','Liver enzymes at baseline','Creatine kinase if muscle symptoms occur'],'Contraindicated in pregnancy.','Contraindicated during breastfeeding.','Used in familial hypercholesterolaemia under specialist care.','Effective; monitor for muscle symptoms.','No routine adjustment.','Contraindicated in active liver disease.',ARRAY['Strong outcome evidence','Flexible dosing time','Potent LDL reduction'],ARRAY['Muscle symptoms in some patients','CYP3A4 interactions'],ARRAY['Report unexplained muscle pain promptly','Diet and exercise remain essential'],'"-statin → HMG-CoA reductase inhibitor."','-statin',E'a-TOR-va-sta-tin','अटोर्-वा-स्टै-टिन',CURRENT_DATE),
('rosuvastatin','Rosuvastatin','Rosuvastatin','Rosuvastatin','Rosuvastatin calcium','Cholesterol','A high-intensity statin with limited CYP3A4 metabolism.',ARRAY['5 mg','10 mg','20 mg','40 mg'],ARRAY['Tablet'],ARRAY['Oral'],'Competitive inhibition of HMG-CoA reductase in the liver.','Produces the greatest LDL reduction per milligram among commonly used statins.','Absorbed with low systemic bioavailability but high hepatic uptake via OATP1B1.','Highly protein bound and hepatoselective.','Minimal metabolism, partly via CYP2C9.','Mainly faecal excretion.','Approximately 20%','About 19 hours','Approximately 88%','Lipid effects over 2-4 weeks','Once-daily dosing',ARRAY['Hypercholesterolaemia','Cardiovascular risk reduction'],ARRAY['Active liver disease','Pregnancy and breastfeeding','Severe renal impairment at higher doses'],ARRAY['Myopathy risk, higher at 40 mg','Proteinuria and haematuria reported at high doses','Asian patients may need lower starting doses'],ARRAY['Myalgia','Headache','Nausea','Constipation'],ARRAY['Rhabdomyolysis','Severe hepatic injury (rare)'],ARRAY['Ciclosporin','Gemfibrozil','Some antiretrovirals','Warfarin (monitor INR)'],ARRAY['Lipid profile','Liver enzymes at baseline','Creatine kinase if muscle symptoms occur'],'Contraindicated in pregnancy.','Contraindicated during breastfeeding.','Used in specific paediatric lipid disorders under specialist care.','Start at a lower dose.','Avoid higher doses in significant renal impairment.','Contraindicated in active liver disease.',ARRAY['High-intensity LDL lowering','Fewer CYP3A4 interactions than atorvastatin'],ARRAY['Dose caution in Asian patients and renal impairment'],ARRAY['Lower starting doses are often appropriate in Indian patients'],'"Rosuvastatin = strongest LDL drop per mg."','-statin',E'roe-soo-va-STA-tin','रोसू-वा-स्टै-टिन',CURRENT_DATE),
('levothyroxine','Levothyroxine','Levothyroxine','Levothyroxine','Levothyroxine sodium','Thyroid','Synthetic thyroxine (T4) used as thyroid hormone replacement.',ARRAY['25 mcg','50 mcg','75 mcg','100 mcg'],ARRAY['Tablet'],ARRAY['Oral'],'Provides exogenous T4 which is deiodinated peripherally to the active hormone T3, restoring normal metabolic function.','Restores euthyroid state; excessive dosing produces features of thyrotoxicosis.','Absorbed mainly from the jejunum and ileum; absorption reduced by food, calcium, iron and coffee.','Highly protein bound to thyroxine-binding globulin.','Peripheral deiodination in liver, kidney and other tissues.','Renal and faecal elimination of metabolites.','Approximately 40-80%, best on an empty stomach','About 7 days in euthyroid adults','Over 99%','Clinical effect over 1-3 weeks','Long, allowing once-daily dosing',ARRAY['Hypothyroidism','Post-thyroidectomy replacement','TSH suppression in selected thyroid cancers'],ARRAY['Untreated adrenal insufficiency','Untreated thyrotoxicosis','Acute myocardial infarction (caution)'],ARRAY['Start low in the elderly and in cardiac disease','Over-replacement risks atrial fibrillation and bone loss','Separate from calcium and iron by at least 4 hours'],ARRAY['Usually none at correct dose','Palpitations, tremor, weight loss and anxiety indicate over-replacement'],ARRAY['Atrial fibrillation and angina with over-replacement','Osteoporosis with prolonged over-replacement'],ARRAY['Calcium and iron salts','Proton pump inhibitors','Soya products','Warfarin (enhanced effect)'],ARRAY['TSH 6-8 weeks after any dose change, then periodically','Symptoms of over or under-replacement'],'Requirements usually increase in pregnancy; therapy must be continued with close monitoring.','Compatible with breastfeeding.','Used in congenital hypothyroidism; prompt treatment is critical.','Start at a lower dose and titrate slowly.','No routine adjustment.','No routine adjustment.',ARRAY['Inexpensive and highly effective','Once-daily dosing'],ARRAY['Absorption is easily disturbed by food and other drugs','Needs regular monitoring'],ARRAY['Take on an empty stomach, 30-60 minutes before breakfast','Keep to the same brand where possible'],'"Levothyroxine = empty stomach, morning, wait before food."','',E'lee-voe-thy-ROX-een','लीवो-थाइ-रॉक्-सीन',CURRENT_DATE),
('furosemide','Furosemide','Furosemide (Frusemide)','Furosemide','Furosemide','Heart','A potent loop diuretic.',ARRAY['20 mg','40 mg','10 mg/mL injection'],ARRAY['Tablet','Injection'],ARRAY['Oral','Intravenous','Intramuscular'],'Inhibits the Na-K-2Cl co-transporter in the thick ascending limb of the loop of Henle, producing marked natriuresis and diuresis.','Rapid, potent diuresis with reduction of preload and oedema.','Variable oral absorption, reduced in decompensated heart failure.','Highly protein bound.','Partly metabolised by glucuronidation.','Mainly renal excretion.','Approximately 50-70% orally, variable','About 1-2 hours (prolonged in renal impairment)','Over 95%','Within 30-60 minutes orally, 5 minutes IV','6-8 hours orally',ARRAY['Oedema in heart failure','Pulmonary oedema','Oedema in renal or hepatic disease','Resistant hypertension'],ARRAY['Anuria','Severe electrolyte depletion','Hypersensitivity'],ARRAY['Hypokalaemia and other electrolyte disturbances','Dehydration and hypotension','Ototoxicity with rapid high-dose IV administration'],ARRAY['Increased urination','Hypokalaemia','Hyponatraemia','Dizziness'],ARRAY['Severe electrolyte disturbance','Acute kidney injury from over-diuresis','Ototoxicity'],ARRAY['Aminoglycosides (ototoxicity)','NSAIDs (reduced effect)','Digoxin (hypokalaemia risk)','Lithium'],ARRAY['Electrolytes especially potassium and sodium','Renal function','Weight and fluid balance','Blood pressure'],'Use only when clearly indicated under medical direction.','Seek medical advice; may reduce milk production.','Used in children under specialist direction.','Higher risk of dehydration, falls and electrolyte disturbance.','Higher doses may be required; monitor closely.','Caution; risk of hepatic encephalopathy with electrolyte shifts.',ARRAY['Rapid and potent diuresis','Oral and IV routes'],ARRAY['Electrolyte disturbance','Frequent urination affects daily routine'],ARRAY['Take in the morning to avoid night-time urination','Monitor potassium'],'"Furosemide = strong loop diuretic; watch potassium."','',E'fyoor-OH-se-mide','फ्यूरो-सी-माइड',CURRENT_DATE),
('aspirin','Aspirin','Aspirin (Acetylsalicylic Acid)','Acetylsalicylic acid','Acetylsalicylic acid','Heart','A salicylate used at low dose as an antiplatelet and at higher dose as an analgesic.',ARRAY['75 mg','150 mg','325 mg'],ARRAY['Tablet','Dispersible tablet','Enteric-coated tablet'],ARRAY['Oral'],'Irreversibly acetylates cyclo-oxygenase-1 in platelets, blocking thromboxane A2 synthesis for the platelet lifespan; higher doses also inhibit COX-2 mediated prostaglandin synthesis.','Low dose gives antiplatelet effect; higher doses provide analgesic, antipyretic and anti-inflammatory effects.','Rapidly absorbed from the stomach and upper small intestine.','Widely distributed; salicylate is highly protein bound.','Hydrolysed to salicylic acid then conjugated in the liver; elimination becomes saturable at high doses.','Renal excretion, increased in alkaline urine.','Approximately 50-75%','Aspirin 15-20 minutes; salicylate 2-3 hours at low dose and longer at high dose','Salicylate 80-90%','Antiplatelet effect within 1 hour of a chewed dose','Antiplatelet effect lasts 7-10 days (platelet lifespan)',ARRAY['Secondary prevention of myocardial infarction and ischaemic stroke','Acute coronary syndrome','Pain and fever at higher doses'],ARRAY['Active peptic ulcer or bleeding','Children and adolescents with viral illness (Reye syndrome risk)','Aspirin-exacerbated respiratory disease','Severe bleeding disorders'],ARRAY['Gastrointestinal bleeding','Reye syndrome in children','Bleeding risk before surgery','Caution in asthma'],ARRAY['Dyspepsia','Bruising','Minor bleeding','Nausea'],ARRAY['Major gastrointestinal or intracranial bleeding','Anaphylactoid reactions','Salicylate toxicity in overdose'],ARRAY['Anticoagulants','Other NSAIDs (including ibuprofen, which can blunt the antiplatelet effect)','Methotrexate','Alcohol'],ARRAY['Signs of bleeding','Haemoglobin in long-term use','Blood pressure'],'Low-dose aspirin is used in specific obstetric indications under specialist direction; avoid high dose especially in the third trimester.','Low doses generally considered acceptable; avoid high doses.','Avoid in children and adolescents with febrile viral illness because of Reye syndrome.','Bleeding risk increases; consider gastroprotection.','Avoid in severe renal impairment.','Avoid in severe hepatic impairment.',ARRAY['Inexpensive with strong cardiovascular evidence','Irreversible platelet effect'],ARRAY['Bleeding and gastric irritation','Not for routine paediatric fever'],ARRAY['Chew the tablet in suspected heart attack for faster action','Take after food to reduce gastric irritation'],'"Aspirin = irreversible COX-1, effect lasts the platelet''s life."','',E'ASS-pi-rin','ऐस्-पि-रिन',CURRENT_DATE),
('clopidogrel','Clopidogrel','Clopidogrel','Clopidogrel','Clopidogrel bisulphate','Heart','A thienopyridine P2Y12 receptor antagonist antiplatelet prodrug.',ARRAY['75 mg','150 mg'],ARRAY['Tablet'],ARRAY['Oral'],'A prodrug converted by hepatic CYP enzymes, chiefly CYP2C19, to an active metabolite that irreversibly blocks the platelet P2Y12 ADP receptor.','Inhibits ADP-mediated platelet aggregation for the lifespan of the platelet.','Rapidly absorbed orally.','Highly protein bound.','Hepatic activation via CYP2C19 with extensive esterase inactivation of most of the dose.','Renal and faecal excretion.','Approximately 50% absorbed, with only a small fraction converted to active metabolite','Active metabolite about 30 minutes; effect far longer','Approximately 94-98%','Within 2 hours with a loading dose','Antiplatelet effect lasts 7-10 days',ARRAY['Acute coronary syndrome','After coronary stenting','Secondary prevention of ischaemic stroke and peripheral arterial disease'],ARRAY['Active pathological bleeding','Severe hepatic impairment','Hypersensitivity'],ARRAY['Bleeding risk, increased with dual antiplatelet therapy','Reduced effectiveness in CYP2C19 poor metabolisers','Stop before elective surgery as advised'],ARRAY['Bruising','Minor bleeding','Diarrhoea','Rash'],ARRAY['Major bleeding','Thrombotic thrombocytopenic purpura (very rare)'],ARRAY['Omeprazole and esomeprazole (reduced activation)','Anticoagulants','NSAIDs','SSRIs'],ARRAY['Signs of bleeding','Full blood count as clinically indicated'],'Use only when clearly indicated under specialist direction.','Generally avoided.','Not usually used in children.','Bleeding risk increases with age.','No routine adjustment.','Avoid in severe hepatic impairment.',ARRAY['Effective alternative or addition to aspirin','Once-daily dosing'],ARRAY['Variable response due to CYP2C19 genetics','Bleeding risk'],ARRAY['Do not stop abruptly after stenting without cardiology advice','Prefer pantoprazole if a PPI is needed'],'"-grel → P2Y12 antiplatelet."','-grel',E'kloe-PID-oh-grel','क्लो-पिडो-ग्रेल',CURRENT_DATE);

-- class links
INSERT INTO public.medicine_classifications (medicine_id, class_id, is_primary)
SELECT m.id, c.id, true FROM (VALUES
('paracetamol','non-opioid-analgesics'),('ibuprofen','nsaids'),('diclofenac','nsaids'),('naproxen','nsaids'),
('amoxicillin','beta-lactams'),('amoxicillin-clavulanic-acid','beta-lactams'),('cefixime','beta-lactams'),('ceftriaxone','beta-lactams'),
('azithromycin','macrolides'),('doxycycline','tetracyclines'),('metronidazole','nitroimidazoles'),
('omeprazole','ppis'),('pantoprazole','ppis'),('ondansetron','antiemetics'),
('cetirizine','antihistamines'),('loratadine','antihistamines'),('salbutamol','bronchodilators'),
('metformin','biguanides'),('glimepiride','sulfonylureas'),
('amlodipine','ccb'),('losartan','arbs'),('telmisartan','arbs'),('furosemide','loop-diuretics'),
('atorvastatin','statins'),('rosuvastatin','statins'),
('aspirin','antiplatelets'),('clopidogrel','antiplatelets'),('levothyroxine','thyroid-hormones')
) AS v(med,cls)
JOIN public.medicines m ON m.slug = v.med
JOIN public.drug_classes c ON c.slug = v.cls;

INSERT INTO public.manufacturers (name) VALUES
('GlaxoSmithKline Pharmaceuticals'),('Cipla'),('Sun Pharmaceutical Industries'),('Abbott India'),('USV'),('Alkem Laboratories'),('Torrent Pharmaceuticals'),('Mankind Pharma'),('Lupin'),('Dr. Reddy''s Laboratories'),('Zydus Lifesciences'),('Macleods Pharmaceuticals');

INSERT INTO public.brands (brand_name, medicine_id, manufacturer_id, composition, strength, dosage_form, route, source, verified, last_verified)
SELECT v.brand, m.id, mf.id, v.comp, v.strength, v.form, 'Oral', 'Manufacturer product information', true, CURRENT_DATE
FROM (VALUES
('Crocin','paracetamol','GlaxoSmithKline Pharmaceuticals','Paracetamol','500 mg','Tablet'),
('Dolo 650','paracetamol','Micro Labs','Paracetamol','650 mg','Tablet'),
('Calpol','paracetamol','GlaxoSmithKline Pharmaceuticals','Paracetamol','500 mg','Tablet'),
('Brufen','ibuprofen','Abbott India','Ibuprofen','400 mg','Tablet'),
('Voveran','diclofenac','Novartis India','Diclofenac sodium','50 mg','Tablet'),
('Mox','amoxicillin','Sun Pharmaceutical Industries','Amoxicillin','500 mg','Capsule'),
('Augmentin','amoxicillin-clavulanic-acid','GlaxoSmithKline Pharmaceuticals','Amoxicillin 500 mg + Clavulanic acid 125 mg','625 mg','Tablet'),
('Azithral','azithromycin','Alembic Pharmaceuticals','Azithromycin','500 mg','Tablet'),
('Doxy-1','doxycycline','USV','Doxycycline','100 mg','Capsule'),
('Taxim-O','cefixime','Alkem Laboratories','Cefixime','200 mg','Tablet'),
('Flagyl','metronidazole','Abbott India','Metronidazole','400 mg','Tablet'),
('Omez','omeprazole','Dr. Reddy''s Laboratories','Omeprazole','20 mg','Capsule'),
('Pan 40','pantoprazole','Alkem Laboratories','Pantoprazole','40 mg','Tablet'),
('Emeset','ondansetron','Cipla','Ondansetron','4 mg','Tablet'),
('Cetzine','cetirizine','Dr. Reddy''s Laboratories','Cetirizine','10 mg','Tablet'),
('Asthalin','salbutamol','Cipla','Salbutamol','100 mcg/puff','Inhaler'),
('Glycomet','metformin','USV','Metformin hydrochloride','500 mg','Tablet'),
('Amaryl','glimepiride','Sanofi India','Glimepiride','2 mg','Tablet'),
('Amlong','amlodipine','Micro Labs','Amlodipine','5 mg','Tablet'),
('Losar','losartan','Unichem Laboratories','Losartan potassium','50 mg','Tablet'),
('Telma','telmisartan','Glenmark Pharmaceuticals','Telmisartan','40 mg','Tablet'),
('Atorva','atorvastatin','Zydus Lifesciences','Atorvastatin','10 mg','Tablet'),
('Rosuvas','rosuvastatin','Sun Pharmaceutical Industries','Rosuvastatin','10 mg','Tablet'),
('Thyronorm','levothyroxine','Abbott India','Levothyroxine sodium','50 mcg','Tablet'),
('Lasix','furosemide','Sanofi India','Furosemide','40 mg','Tablet'),
('Ecosprin','aspirin','USV','Aspirin','75 mg','Tablet'),
('Clopilet','clopidogrel','Sun Pharmaceutical Industries','Clopidogrel','75 mg','Tablet')
) AS v(brand,med,maker,comp,strength,form)
JOIN public.medicines m ON m.slug = v.med
LEFT JOIN public.manufacturers mf ON mf.name = v.maker;

INSERT INTO public.manufacturers (name) VALUES ('Micro Labs'),('Novartis India'),('Alembic Pharmaceuticals'),('Sanofi India'),('Unichem Laboratories'),('Glenmark Pharmaceuticals') ON CONFLICT DO NOTHING;
UPDATE public.brands b SET manufacturer_id = mf.id FROM public.manufacturers mf
WHERE b.manufacturer_id IS NULL AND mf.name = CASE b.brand_name
  WHEN 'Dolo 650' THEN 'Micro Labs' WHEN 'Amlong' THEN 'Micro Labs' WHEN 'Voveran' THEN 'Novartis India'
  WHEN 'Azithral' THEN 'Alembic Pharmaceuticals' WHEN 'Amaryl' THEN 'Sanofi India' WHEN 'Lasix' THEN 'Sanofi India'
  WHEN 'Losar' THEN 'Unichem Laboratories' WHEN 'Telma' THEN 'Glenmark Pharmaceuticals' END;

INSERT INTO public.medicine_references (medicine_id, reference_id)
SELECT m.id, r.id FROM public.medicines m CROSS JOIN public.references r
WHERE r.source_name IN ('National List of Essential Medicines (NLEM), India','KD Tripathi, Essentials of Medical Pharmacology','British National Formulary (BNF)');

INSERT INTO public.drug_interactions (medicine_a_id, medicine_b_id, severity, description, mechanism, clinical_significance, professional_consideration)
SELECT a.id, b.id, v.sev, v.descr, v.mech, v.sig, v.cons FROM (VALUES
('aspirin','ibuprofen','moderate','Ibuprofen can reduce the cardioprotective antiplatelet effect of low-dose aspirin.','Competition for the COX-1 acetylation site on platelets.','May reduce cardiovascular protection when used regularly together.','Where both are needed, timing separation or an alternative analgesic is often considered.'),
('clopidogrel','omeprazole','major','Omeprazole reduces conversion of clopidogrel to its active metabolite.','CYP2C19 inhibition by omeprazole.','Reduced antiplatelet effect with possible increased thrombotic risk.','Pantoprazole is commonly preferred when a PPI is required with clopidogrel.'),
('metformin','furosemide','moderate','Diuretic-induced dehydration can precipitate metformin accumulation.','Reduced renal clearance of metformin during volume depletion.','Increased risk of lactic acidosis in dehydration or acute illness.','Renal function monitoring and sick-day guidance are standard practice.'),
('losartan','ibuprofen','moderate','NSAIDs can reduce the antihypertensive effect of ARBs and impair renal function.','Prostaglandin inhibition reduces renal perfusion and sodium excretion.','Blood pressure rise and risk of acute kidney injury, especially with a diuretic.','Renal function and blood pressure monitoring are advised.'),
('levothyroxine','omeprazole','moderate','Reduced gastric acidity can decrease levothyroxine absorption.','Higher gastric pH reduces dissolution and absorption.','Possible rise in TSH and reduced control of hypothyroidism.','TSH monitoring after starting or stopping the PPI is advised.'),
('atorvastatin','azithromycin','moderate','Macrolides may increase statin exposure and myopathy risk.','Inhibition of CYP3A4 and transporter-mediated clearance.','Increased risk of muscle symptoms and rarely rhabdomyolysis.','Muscle symptom review during concurrent therapy is advised.'),
('aspirin','clopidogrel','moderate','Combined antiplatelet therapy increases bleeding risk.','Additive inhibition of platelet function by two different pathways.','Higher bleeding risk; the combination is nonetheless indicated in specific cardiac situations.','Duration of dual therapy is determined by the treating specialist.'),
('metronidazole','warfarin-placeholder','moderate','placeholder','placeholder','placeholder','placeholder')
) AS v(a,b,sev,descr,mech,sig,cons)
JOIN public.medicines a ON a.slug = v.a
JOIN public.medicines b ON b.slug = v.b;

INSERT INTO public.flashcards (question, answer, topic, difficulty, medicine_id)
SELECT v.q, v.a, v.t, v.d, m.id FROM (VALUES
('Which class does losartan belong to?','ARB — Angiotensin II receptor blocker','Drug Classes','easy','losartan'),
('What is the antidote for paracetamol overdose?','N-acetylcysteine','Emergency','easy','paracetamol'),
('What is the main mechanism of omeprazole?','Irreversible inhibition of the gastric H+/K+-ATPase (proton pump)','Mechanism','easy','omeprazole'),
('How is metformin eliminated?','Excreted unchanged by the kidneys; it is not metabolised','ADME','medium','metformin'),
('Why is doxycycline avoided in pregnancy and young children?','Risk of tooth discolouration and effects on developing bone','Safety','easy','doxycycline'),
('How long does the antiplatelet effect of aspirin last?','7-10 days, the lifespan of the platelet, because COX-1 inhibition is irreversible','Pharmacodynamics','medium','aspirin'),
('Which enzyme activates clopidogrel?','CYP2C19 in the liver','ADME','medium','clopidogrel'),
('What is the classic dose-related adverse effect of amlodipine?','Ankle oedema','Adverse Effects','easy','amlodipine'),
('When should levothyroxine be taken?','On an empty stomach, 30-60 minutes before breakfast','Counselling','easy','levothyroxine'),
('Which electrolyte must be monitored with furosemide?','Potassium (hypokalaemia risk)','Monitoring','easy','furosemide'),
('What must be strictly avoided with metronidazole?','Alcohol, due to a disulfiram-like reaction','Safety','easy','metronidazole'),
('Which ARB has the longest half-life?','Telmisartan, about 24 hours','Pharmacokinetics','medium','telmisartan'),
('What is the mechanism of salbutamol?','Beta-2 adrenoceptor agonism relaxing bronchial smooth muscle','Mechanism','easy','salbutamol'),
('Why is ondansetron used cautiously in cardiac patients?','It can prolong the QT interval','Safety','medium','ondansetron'),
('What does clavulanic acid add to amoxicillin?','Beta-lactamase inhibition, protecting amoxicillin from breakdown','Mechanism','easy','amoxicillin-clavulanic-acid')
) AS v(q,a,t,d,med)
JOIN public.medicines m ON m.slug = v.med;

INSERT INTO public.flashcards (question, answer, topic, difficulty) VALUES
('What does ADME stand for?','Absorption, Distribution, Metabolism, Excretion','ADME','easy'),
('Define bioavailability.','The fraction of an administered dose that reaches the systemic circulation unchanged','Pharmacokinetics','easy'),
('Define half-life.','The time taken for the plasma concentration of a drug to fall by half','Pharmacokinetics','easy'),
('What does the suffix -prazole indicate?','Proton pump inhibitor','Suffixes','easy'),
('What does the suffix -pril indicate?','ACE inhibitor','Suffixes','easy'),
('Pharmacokinetics vs pharmacodynamics?','Pharmacokinetics is what the body does to the drug; pharmacodynamics is what the drug does to the body','Concepts','easy');

INSERT INTO public.quiz_questions (question, question_type, options, correct_answer, explanation, topic, difficulty) VALUES
('Losartan belongs to which drug class?','mcq',ARRAY['ACE inhibitor','ARB','Beta blocker','Calcium channel blocker'],'ARB','Losartan blocks the angiotensin II AT1 receptor. The -sartan suffix is a memory aid for ARBs.','Drug Classes','easy'),
('Which medicine is the usual first-line oral therapy in type 2 diabetes?','mcq',ARRAY['Glimepiride','Metformin','Insulin glargine','Amlodipine'],'Metformin','Metformin is weight neutral, does not intrinsically cause hypoglycaemia and has strong long-term evidence.','Pharmacology','easy'),
('The antidote for paracetamol overdose is:','mcq',ARRAY['Naloxone','Flumazenil','N-acetylcysteine','Atropine'],'N-acetylcysteine','N-acetylcysteine replenishes glutathione, which detoxifies the reactive metabolite NAPQI.','Emergency','easy'),
('Which suffix usually indicates a proton pump inhibitor?','mcq',ARRAY['-sartan','-prazole','-olol','-statin'],'-prazole','Omeprazole, pantoprazole and rabeprazole are proton pump inhibitors.','Medical Terms','easy'),
('Metformin is mainly eliminated by:','mcq',ARRAY['Hepatic metabolism','Renal excretion unchanged','Biliary excretion after conjugation','Exhalation'],'Renal excretion unchanged','Metformin is not metabolised; renal impairment therefore raises the risk of accumulation.','ADME','medium'),
('Which adverse effect is characteristic of amlodipine?','mcq',ARRAY['Dry cough','Ankle oedema','Hyperkalaemia','Bradycardia'],'Ankle oedema','Dihydropyridine calcium channel blockers cause dose-related peripheral oedema.','Pharmacology','easy'),
('Doxycycline should generally be avoided in:','mcq',ARRAY['Adults with pneumonia','Pregnancy','Acne','Rickettsial infection'],'Pregnancy','Tetracyclines affect developing teeth and bone.','Pharmacology','easy'),
('Aspirin''s antiplatelet effect lasts about:','mcq',ARRAY['4 hours','24 hours','7-10 days','30 days'],'7-10 days','COX-1 inhibition in platelets is irreversible, so the effect lasts the platelet lifespan.','Pharmacodynamics','medium'),
('Which PPI is usually preferred alongside clopidogrel?','mcq',ARRAY['Omeprazole','Esomeprazole','Pantoprazole','Lansoprazole'],'Pantoprazole','Pantoprazole has less CYP2C19 inhibition, so it interferes less with clopidogrel activation.','Interactions','hard'),
('Bioavailability refers to:','mcq',ARRAY['How fast a drug is excreted','The fraction of the dose reaching systemic circulation unchanged','The volume the drug distributes into','The strength of receptor binding'],'The fraction of the dose reaching systemic circulation unchanged','It is a key absorption parameter within ADME.','ADME','easy'),
('Metronidazole must not be taken with:','mcq',ARRAY['Milk','Alcohol','Vitamin C','Paracetamol'],'Alcohol','A disulfiram-like reaction can occur with flushing, nausea and vomiting.','Safety','easy'),
('Pharmacodynamics is best described as:','mcq',ARRAY['What the body does to the drug','What the drug does to the body','How a drug is manufactured','How a drug is stored'],'What the drug does to the body','Pharmacokinetics is the reverse: what the body does to the drug.','Concepts','easy'),
('Salbutamol acts on which receptor?','mcq',ARRAY['Beta-1','Beta-2','Alpha-1','Muscarinic'],'Beta-2','Beta-2 agonism relaxes bronchial smooth muscle.','Mechanism','easy'),
('Levothyroxine is best taken:','mcq',ARRAY['With breakfast','On an empty stomach before breakfast','With calcium tablets','At bedtime with milk'],'On an empty stomach before breakfast','Food, calcium and iron reduce absorption.','Counselling','easy'),
('Which class does azithromycin belong to?','mcq',ARRAY['Beta-lactam','Macrolide','Tetracycline','Fluoroquinolone'],'Macrolide','Azithromycin binds the 50S ribosomal subunit.','Drug Classes','easy'),
('Furosemide acts on which part of the nephron?','mcq',ARRAY['Proximal tubule','Thick ascending limb of the loop of Henle','Distal convoluted tubule','Collecting duct'],'Thick ascending limb of the loop of Henle','It inhibits the Na-K-2Cl co-transporter there.','Pharmacology','medium'),
('Statins inhibit which enzyme?','mcq',ARRAY['HMG-CoA reductase','Cyclo-oxygenase','ACE','Xanthine oxidase'],'HMG-CoA reductase','This is the rate-limiting step of hepatic cholesterol synthesis.','Mechanism','easy'),
('Ondansetron blocks which receptor?','mcq',ARRAY['Dopamine D2','Histamine H1','Serotonin 5-HT3','Muscarinic M1'],'Serotonin 5-HT3','It acts on vagal afferents and the chemoreceptor trigger zone.','Mechanism','medium'),
('ACE inhibitors commonly cause which distinctive adverse effect?','mcq',ARRAY['Ankle oedema','Dry cough','Hair loss','Tinnitus'],'Dry cough','Bradykinin accumulation is the usual explanation; ARBs avoid this.','Pharmacology','easy'),
('Which statement about drug-name suffixes is correct?','true_false',ARRAY['True','False'],'False','Suffixes are memory aids only; exceptions exist and the actual record must always be checked. (Statement: suffixes are absolute classification rules.)','Medical Terms','easy');

INSERT INTO public.mnemonics (title, content, explanation, class_id)
SELECT v.t, v.c, v.e, dc.id FROM (VALUES
('ARBs end in -sartan','Losartan, Valsartan, Telmisartan, Candesartan, Olmesartan','All block the angiotensin II AT1 receptor.','arbs'),
('PPIs end in -prazole','Omeprazole, Pantoprazole, Rabeprazole, Esomeprazole','All irreversibly block the gastric proton pump.','ppis'),
('Statins end in -statin','Atorvastatin, Rosuvastatin, Simvastatin','All inhibit HMG-CoA reductase.','statins'),
('CCBs end in -dipine','Amlodipine, Nifedipine, Felodipine','Dihydropyridine calcium channel blockers; ankle oedema is the clue.','ccb')
) AS v(t,c,e,cls)
JOIN public.drug_classes dc ON dc.slug = v.cls;
